#!/usr/bin/env bash
# Install site + SSL monitoring as cron jobs for the current user.
# Idempotent: re-running just refreshes the crontab block.
# Requires:
#   - openclaw already installed (we read the bot token from ~/.openclaw/openclaw.json)
#   - your Telegram user id (the bot DM'd it to you on /start)

set -euo pipefail

if [ "$(id -u)" -eq 0 ]; then
  echo "Run this as the deploy user (no sudo)." >&2
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
ENV_DIR="$HOME/.openclaw-monitor"
ENV_FILE="$ENV_DIR/.env"

mkdir -p "$ENV_DIR/state"

# Extract bot token from OpenClaw config
OC_CONFIG="$HOME/.openclaw/openclaw.json"
if [ ! -r "$OC_CONFIG" ]; then
  echo "Cannot read $OC_CONFIG. Is OpenClaw installed?" >&2
  exit 1
fi

BOT_TOKEN="$(jq -r '.channels.telegram.token // .channels.telegram.botToken // empty' "$OC_CONFIG" 2>/dev/null || true)"
if [ -z "$BOT_TOKEN" ] || [ "$BOT_TOKEN" = "null" ]; then
  # try a broader search
  BOT_TOKEN="$(grep -oE '[0-9]{8,12}:[A-Za-z0-9_-]{30,}' "$OC_CONFIG" | head -n1 || true)"
fi
if [ -z "$BOT_TOKEN" ]; then
  echo "Could not auto-find Telegram bot token in $OC_CONFIG." >&2
  read -r -p "Paste your Telegram bot token: " BOT_TOKEN
fi

# Ask for chat id
DEFAULT_CHAT_ID=""
if [ -r "$ENV_FILE" ]; then
  DEFAULT_CHAT_ID="$(grep -E '^TELEGRAM_CHAT_ID=' "$ENV_FILE" | tail -n1 | cut -d= -f2- || true)"
fi
if [ -n "$DEFAULT_CHAT_ID" ]; then
  read -r -p "Telegram chat id [$DEFAULT_CHAT_ID]: " CHAT_ID
  CHAT_ID="${CHAT_ID:-$DEFAULT_CHAT_ID}"
else
  echo "Your Telegram user id was shown when you sent /start to the bot."
  read -r -p "Telegram chat id: " CHAT_ID
fi

if [ -z "$CHAT_ID" ]; then
  echo "chat id required" >&2
  exit 1
fi

# Write .env (mode 600)
umask 077
cat > "$ENV_FILE" <<EOF
# Generated by 03-install-monitoring.sh — keep private (mode 600)
TELEGRAM_BOT_TOKEN=$BOT_TOKEN
TELEGRAM_CHAT_ID=$CHAT_ID
EOF
chmod 600 "$ENV_FILE"
echo "✓ wrote $ENV_FILE (mode 600)"

# Make scripts executable
chmod +x "$SCRIPT_DIR/site-check.sh" "$SCRIPT_DIR/ssl-check.sh" "$SCRIPT_DIR/lib/notify-telegram.sh"

# Test notification
echo
echo "▶ Sending test message to Telegram..."
if "$SCRIPT_DIR/lib/notify-telegram.sh" "🦞 OpenClaw monitor installed on $(hostname) — site checks every 5 min, SSL every 6 hr."; then
  echo "✓ test message sent (check Telegram)"
else
  echo "✗ test message failed — check your bot token / chat id and try again." >&2
  exit 1
fi

# Install crontab block
BEGIN_MARK="# >>> openclaw-monitor >>>"
END_MARK="# <<< openclaw-monitor <<<"

CRON_BLOCK="$BEGIN_MARK
# Managed by openclaw/scripts/03-install-monitoring.sh — do not edit by hand.
*/5 * * * * $SCRIPT_DIR/site-check.sh >/dev/null 2>&1
17 */6 * * * $SCRIPT_DIR/ssl-check.sh  >/dev/null 2>&1
$END_MARK"

EXISTING="$(crontab -l 2>/dev/null || true)"
FILTERED="$(printf '%s\n' "$EXISTING" | awk -v b="$BEGIN_MARK" -v e="$END_MARK" '
  $0==b {skip=1; next}
  $0==e {skip=0; next}
  !skip
')"

{
  printf '%s\n' "$FILTERED"
  printf '%s\n' "$CRON_BLOCK"
} | sed '/^$/N;/^\n$/D' | crontab -

echo "✓ crontab updated:"
crontab -l | sed -n "/$BEGIN_MARK/,/$END_MARK/p"

echo
echo "▶ Running site-check once to seed state..."
"$SCRIPT_DIR/site-check.sh"
echo "✓ initial run complete (no alerts on first run unless a site is down)"
echo
echo "Logs:   tail -f ~/.openclaw-monitor/monitor.log"
echo "State:  ls ~/.openclaw-monitor/state/"
echo "Stop:   crontab -e   # remove the openclaw-monitor block"
